build:
	/Users/dima/Downloads/clang+llvm-5.0.1-final-x86_64-apple-darwin/bin/clang++ hello.cpp -std=c++2a -fcoroutines-ts -stdlib=libc++ -o hello && ./hello
	/Users/dima/Downloads/clang+llvm-6.0.0-x86_64-apple-darwin/bin/clang++ generator.cpp -std=c++2a -fcoroutines-ts -stdlib=libc++ -o generator && ./generator
